USE CustomerOrderViewer;

INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Lawrence', NULL, 'Keener', 27);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Lynette', NULL, 'Snyder', 34);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Jesus', NULL, 'Dimick', 34);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Betty', NULL, 'Hall', 21);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Maryann', NULL, 'Castro', 43);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Michael ', NULL, 'Cooper', 45);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Alfred', NULL, 'Cervantes', 21);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Megan', NULL, 'Read', 22);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Melissa', NULL, 'Sherlock', 31);
INSERT INTO [dbo].[Customer] (FirstName, MiddleName, LastName, Age) VALUES ('Kori', NULL, 'Higgins', 57);

INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Duracell Alkaline AA Batteries', 15.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Kirkland Signature Moist Flushable Wipes', 14.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Carnation Breakfast Essentials', 12.59);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Capri Sun Variety Pack', 7.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Mott''s Clamato Juice', 11.79);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Dr. Pepper', 9.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Mountain Dew', 9.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Pepsi Cola', 9.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('Sprite', 10.99);
INSERT INTO [dbo].[Item] ([Description], Price) VALUES ('San Pellegrino Mineral Water', 17.99);

INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 3);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 4);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 5);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (1, 6);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (2, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (2, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (2, 3);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (3, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (4, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (4, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (5, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (6, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (6, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (7, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (7, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (8, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (8, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 1);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 2);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 3);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 4);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 5);
INSERT INTO [dbo].[CustomerOrder] (CustomerId, ItemId) VALUES (9, 6);
